/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "EEPROM.h"

int main(void)
{
	RCC_GPIOA_CLK_EN() ;
	RCC_GPIOB_CLK_EN() ;
	RCC_AFIO_CLK_EN() ;

	//Test case 1
	uint8_t ch1[]={0x1,0x2,0x3,0x4,0x5,0x6,0x7} ;
	uint8_t ch2[7]={0} ;

	EEPROM_Init() ;
	EEPROM_Write_Nbyte(0XAF, ch1, 7) ;
	EEPROM_Read_byte(0XAF, ch2, 7) ;


	//Test case 2
	ch1[0] = 0xA ;
	ch1[1] = 0xB ;
	ch1[2] = 0xC ;
	ch1[3] = 0xD ;

	EEPROM_Write_Nbyte(0XFFF, ch1, 4) ;
	EEPROM_Read_byte(0XFFF, ch2, 4) ;


	while(1)
	{

	}
}
