/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "GPIO.h"


int main(void)
{
	vuint32 i ;
	GPIO_PinConfig_t Config_Pin ;
	//CLOCK ENABLE
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();

	//PA1 is input floating
	Config_Pin.GPIO_MODE = GPIO_MODE_INPUT_FLO ;
	Config_Pin.GPIO_PinNumber = GPIO_PIN_1 ;
	MCAL_GPIO_Init(GPIOA, &Config_Pin) ;
	//====================================================/

	//PB1 is output push pull
	Config_Pin.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	Config_Pin.GPIO_PinNumber = GPIO_PIN_1 ;
	Config_Pin.GPIO_Output_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_Init(GPIOB, &Config_Pin) ;
	//====================================================/

	//PA13 is input floating
	Config_Pin.GPIO_MODE = GPIO_MODE_INPUT_FLO ;
	Config_Pin.GPIO_PinNumber = GPIO_PIN_13 ;
	MCAL_GPIO_Init(GPIOA, &Config_Pin) ;
	//====================================================/

	//PB13 is output push pull
	Config_Pin.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	Config_Pin.GPIO_PinNumber = GPIO_PIN_13 ;
	Config_Pin.GPIO_Output_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_Init(GPIOB, &Config_Pin) ;
	//====================================================/
	while(1)
	{
		if ( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0 )
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1) ;
			//while( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET );
		}

		if ( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1 )
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13) ;
		}

		for(i =0 ;i<=70000;i++);



	}

}
