/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "UART.h"
#include "GPIO.h"
uint16_t data ;
void clock_init()
{
	RCC_GPIOA_CLK_EN() ;
	RCC_GPIOB_CLK_EN() ;
	RCC_AFIO_CLK_EN() ;
}
void receive_handler(void)
{
	MCAL_UART_ReceiveData(USART1, &data , disable) ;
	MCAL_UART_SendData(USART1, &data, enable) ;
}

int main(void)
{

	clock_init() ;
	UART_Config_t config ;
	config.BaudRte = UART_BaudRate_115200 ;
	config.HWFlowCTL = UART_FlowCTL_NONE ;
	config.IRQ_Enable = UART_IRQ_Enable_RXNEIE ;
	config.P_IRQ_CallBack = receive_handler ;
	config.LoadLength = UART_LoadLength_8B ;
	config.StopBits = UART_StopBits_1 ;
	config.USART_mode = UART_Mode_TX_RX ;
	config.parity = UART_Parity_NONE ;
	MCAL_UART_Init(USART1, &config) ;
	MCAL_UART_GPIO_Set_Pins(USART1) ;

	while(1)
	{

	}

}
