/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STD_TYPES.h"


//register addresses of GPIOA
#define GPIOA_BASE      0x40010800
#define GPIOA_CRH       *(vuint32 *)(GPIOA_BASE+0x04)
#define GPIOA_ODR		*(vuint32 *)(GPIOA_BASE+0x0c)
#define GPIO_CRL		*(vuint32 *)(GPIOA_BASE+0x00)

//register addresses of RCC
#define RCC_BASE        0x40021000
#define RCC_APB2ENR		*(vuint32 *)(RCC_BASE+0x18)

//register addresses of EXTI
#define EXTI_BASE       0x40010400
#define EXTI_IMR		*(vuint32 *)(EXTI_BASE+0x00)
#define EXTI_RTSR		*(vuint32 *)(EXTI_BASE+0x08)
#define EXTI_FTSR		*(vuint32 *)(EXTI_BASE+0x0c)
#define EXTI_PR			*(vuint32 *)(EXTI_BASE+0x14)

//AFIO registers
#define AFIO_BASE       0x40010000
#define AFIO_EXTICR1	*(vuint32 *)(AFIO_BASE+0x08)


#define NVIC_EXIE0		*(vuint32 *)(0xE000E100)
void clock_init()
{
	//init clock for GPIOA
	RCC_APB2ENR |=(1<<2);

	//init clock for AFIO
	RCC_APB2ENR |= (1<<0);
}
void GPIO_INIT()
{
	//Pin 13 PORTA is output pin
	GPIOA_CRH &= 0Xff0fffff;
	GPIOA_CRH |= 0X00200000;

	//  Pin A0 : Floating input (reset state)
	GPIO_CRL |=(0b01 << 2);
}

int main(void)
{
	clock_init();
	GPIO_INIT();
	//EXTI configuration to PORTA0
	AFIO_EXTICR1 |= (0b000 << 0);

	//detect rising edge for line 0
	EXTI_RTSR |= (1<<0);

	//enable bit mask for line 0
	EXTI_IMR |= (1<<0);

	//enable NVIC interrupt
	NVIC_EXIE0 |= (1<<6) ;

	while(1);

}
void EXTI0_IRQHandler (void)
{
	//clear pending request at line 0 by writing one to it.
	EXTI_PR |= (1<<0);

	//toggle led which is connected to Pin 13
	GPIOA_ODR ^= (1<<13) ;
}
