/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STD_TYPES.h"


//register addresses of GPIOA
#define GPIOA_BASEA      0x40010800
#define GPIOA_CRH       *(vuint32 *)(GPIOA_BASEA+0x04)
#define GPIOA_ODR		*(vuint32 *)(GPIOA_BASEA+0x0c)
#define GPIOA_CRL		*(vuint32 *)(GPIOA_BASEA+0x00)
#define GPIOA_IDR		*(vuint32 *)(GPIOA_BASEA+0x08)


//register addresses of GPIOB
#define GPIOB_BASEB      0x40010C00
#define GPIOB_CRH       *(vuint32 *)(GPIOB_BASEB+0x04)
#define GPIOB_ODR		*(vuint32 *)(GPIOB_BASEB+0x0c)
#define GPIOB_CRL		*(vuint32 *)(GPIOB_BASEB+0x00)
#define GPIOB_IDR		*(vuint32 *)(GPIOB_BASEB+0x08)

//register addresses of RCC
#define RCC_BASE        0x40021000
#define RCC_APB2ENR		*(vuint32 *)(RCC_BASE+0x18)


//#define input_A1   ((GPIOA_IDR&(1<<1))>>1)
//#define input_A13  ((GPIOA_IDR&(1<<13))>>13)
void clock_init()
{
	//init clock for GPIOA
	RCC_APB2ENR |=(1<<2);

	//init clock for GPIOB
	RCC_APB2ENR |=(1<<3);
}
void GPIO_INIT()
{
	GPIOA_CRL = 0x0;
	GPIOB_CRL = 0x0;
	//PA1 is input floating
	GPIOA_CRL |=(1<<6);

	//PB1 is output push pull
	GPIOB_CRL &=~(0b11<<6);
	GPIOB_CRL |= (0b01<<4);


	//PA13 is input floating
	GPIOA_CRH &= ~(0b11<<20);
	GPIOA_CRH |= (0b01<<22);

	//PB13 is output push pull
	GPIOB_CRH |= (0b01<<20);
	GPIOB_CRH &= ~(0b11<<22);

}

int main(void)
{
	vsint32 i;
	clock_init();
	GPIO_INIT();

	while(1)
	{
		if(((GPIOA_IDR&(1<<1))>>1) == 0)
		{
			GPIOB_ODR = (1<<1);
			while((( GPIOA_IDR & (1<<1) ) >>1) == 0);
		}
		if(((GPIOA_IDR&(1<<13))>>13) == 1)
		{
			GPIOB_ODR ^= (1<<13);

		}
		for(i =0 ; i <400 ; i++);
	}

}
