/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "lcd.h"
#include "EXTI.h"
vuint32 IRQ_Flag = 0;
void delay_ms(uint32_t time) ;
void EXTI9PB9_CallBack()
{
	IRQ_Flag = 1 ;
	LCD_WRITE_STRING("IRQ EXTI9 is happened");
	delay_ms(1000) ;
}
int main(void)
{
	RCC_GPIOA_CLK_EN() ;
	RCC_GPIOB_CLK_EN() ;
	RCC_AFIO_CLK_EN() ;
	LCD_INIT() ;
	EXTI_PinConfig_t Pin_Config ;
	Pin_Config.EXTI_Pin = EXTI9PB9 ;
	Pin_Config.IRQ_EN = EXTI_IRQ_Enabled ;
	Pin_Config.Trigger_Case =EXTI_Trigger_FALLING ;
	Pin_Config.P_IRQ_CallBck = EXTI9PB9_CallBack ;
	IRQ_Flag = 1;
	MCAL_EXTI_GPIO_Init(&Pin_Config) ;
	while(1)
	{
		if(IRQ_Flag == 1)
		{
		LCD_clear_screen() ;
		IRQ_Flag = 0 ;
		}
	}
}
